[package]
name = "tokio_postgres_example"
version = "0.1.0"
authors = ["Jinhua Luo <home_king@163.com>"]
edition = "2018"

[dependencies]
tokio = {version="0.2.10", features = ["full"]}
tokio-postgres = {git="https://github.com/sfackler/rust-postgres"}
futures = "0.3.1"
bytes = "0.5.4"
